"""empty message

Revision ID: 5f2e8f19f680
Revises: b1dd89e7fdac
Create Date: 2022-06-01 11:17:54.328011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2e8f19f680'
down_revision = 'b1dd89e7fdac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('venues', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'description')
    op.drop_column('Artist', 'venues')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
