"""empty message

Revision ID: 9e2157cc6f71
Revises: 68c1b01a9f73
Create Date: 2022-06-04 10:18:22.878341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e2157cc6f71'
down_revision = '68c1b01a9f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('upcoming', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'upcoming')
    # ### end Alembic commands ###
